# -*- coding: utf-8 -*-
"""Visualising Streaming Data with Streamlit II_MESO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyBPeK6pchVtMu2QTKXi0Xjy5RAf6eMx

# **Introduction**
In this project, you will create a real-time data visualization dashboard using Streamlit to analyze
streaming data from Reddit to identify fraud in telecommunications. The project will involve
connecting to Reddit's API, collecting real-time posts, processing the posts to extract useful
information, and visualizing the data using Streamlit.

# **Problem Statement**
Fraud in telecommunications is a significant problem that costs the industry billions of dollars
annually. Fraudsters use various techniques to exploit telecom infrastructure weaknesses,
including hacking into phone systems, stealing identities, and exploiting vulnerabilities in billing
systems. The challenge for telecom companies is to detect and prevent fraud in real-time before
it causes significant financial damage.
Your task is to develop a real-time data visualization dashboard that monitors Reddit for
mentions of telecoms fraud and other related keywords, such as "telecoms scam", "phone
fraud", "billing fraud", and "identity theft". You will extract useful information from the posts, such
as the post text, user name, subreddit, and date/time, and use this information to analyze the
data for patterns and trends related to telecom fraud.
"""

!pip install praw

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import praw
import re
import matplotlib.pyplot as plt
import altair as alt
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import streamlit as st
import pandas as pd
from PIL import Image

reddit = praw.Reddit(client_id='2Se3vbeXMiIrLixTwQgtHw',
                     client_secret='FxU9wFvlwapPrsOgYDuk0ZhzOlqRyA',
                     user_agent='busaz')

#Words to monitor for telecom fraud
words = ['telecoms scam', 'phone fraud', 'billing fraud', 'identity theft']

posts = []
for word in words:
    subreddit = reddit.subreddit('all')
    for post in subreddit.search(keyword, limit=20, sort='new'):
        posts.append({
            'post_text': post.title,
            'user_name': post.author.name,
            'subreddit': post.subreddit.display_name,
            'date': pd.to_datetime(post.created_utc, unit='s'),
        })

#  DataFrame from the fetched posts
fraud_df = pd.DataFrame(posts)

# Set the title and description of your Streamlit application
st.title('Telecom Fraud  Dashboard')
st.markdown('Real-time data visualization of telecom fraud')



# Display the data table
st.subheader('Data Table')
st.dataframe(fraud_df)

# bar chart  number of fraud mentions 
st.subheader('Fraud Mentions by Subreddit')
chart_data = fraud_df['subreddit'].value_counts()
st.bar_chart(chart_data)

#line chart showing the frequency of fraud mentions over time
st.subheader('Fraud Mentions Over Time')
chart_data = fraud_df['date'].value_counts().sort_index()
st.line_chart(chart_data)